Uretim_Operation/Models/Notifications.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Uretim_Operation.Models
{
    public class Notifications
    {
        [Key]
        public int Id { get; set; }
        public int IsNo { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime BaslangicTarihi { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime BitisTarihi { get; set; }
        public TimeSpan ToplamSure { get; set; }
        public string Statu { get; set; }
        public string DurusNedeni { get; set; }
    }
}

Uretim_Operation/Controllers/NotificationsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Uretim_Operation.Data;
using Uretim_Operation.Models;

namespace Uretim_Operation.Controllers
{
    public class NotificationsController : Controller
    {

        private readonly UOBContext _context;

        public NotificationsController(UOBContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
           return View(_context.Notifications.ToList());
        }

        public JsonResult CreateNotification(int _IsNo, DateTime _BaslangicTarihi, DateTime _BitisTarihi, TimeSpan _ToplamSure, string _Statu, string _DurusNedeni)
        {
            
            Notifications notifications = new Notifications();
            notifications.IsNo = _IsNo;
            notifications.BaslangicTarihi = _BaslangicTarihi;
            notifications.BitisTarihi = _BitisTarihi;
            var span = _BitisTarihi.Subtract(_BaslangicTarihi);
            var minute = span.TotalMinutes.ToString();
            notifications.ToplamSure = span;
            notifications.Statu = _Statu;
            var m = Int32.Parse(minute);

            if (m > 0 && m <=15 )
            {
                notifications.DurusNedeni = "Çay Molası";
            }
            else if (m>15 && m<=30)
            {
                notifications.DurusNedeni = "Yemek Molası";
            }
            

            _context.Add(notifications);
            var result = _context.SaveChanges();

            return Json(result);
        }

    }
}

Uretim_Operation/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Uretim_Operation.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Uretim_Operation/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Uretim_Operation.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Uretim_Operation/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Uretim_Operation.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Uretim_Operation/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Uretim_Operation/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Uretim_Operation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Uretim_Operation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Uretim_Operation - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Uretim_Operation/Views/Notifications/Index.cshtml
@model IEnumerable<Uretim_Operation.Models.Notifications>


<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <p>
        <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Bildirim Ekle</button>
    </p>


    <div class="justify-content-md-center">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.BaslangicTarihi)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BitisTarihi)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ToplamSure)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Statu)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DurusNedeni)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.BaslangicTarihi)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BitisTarihi)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ToplamSure)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Statu)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DurusNedeni)
                        </td>
                        @*<td>
                                <a asp-action="Edit" asp-route-id="@item.IsNo">Edit</a> |
                                <a asp-action="Details" asp-route-id="@item.IsNo">Details</a> |
                                <a asp-action="Delete" asp-route-id="@item.IsNo">Delete</a>
                            </td>*@
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Modal Header</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="d-flex justify-content-center">
                        <div class="col-md-3">
                            <label>* İş No:</label>
                            <input id="isNo" type="text" class="form-control input-sm" />
                        </div>
                    </div>
                    <div class="d-flex justify-content-center">
                        <div class="col-md-3">
                            <label>* Baslangıc Tarihi:</label>
                            <input id="baslangicTarihi" type="datetime-local" value="@(DateTime.Now.ToString("yyyy-MM-dd"))"
                                   class="form-control input-sm" />
                        </div>
                    </div>
                    <div class="d-flex justify-content-center">
                        <div class="col-md-3">
                            <label>* Bitis Tarihi:</label>
                            <input id="bitisTarihi" type="datetime-local"
                                   value="@(DateTime.Now.AddYears(1).ToString("yyyy-MM-dd"))"
                                   class="form-control input-sm" />
                        </div>
                    </div>
                    @*<div class="d-flex justify-content-center">
                        <div class="col-md-3">
                            <label>* Toplam Süre:</label>
                            <input id="toplamSure" type="time" class="form-control input-sm" />
                        </div>
                    </div>*@
                    <div class="d-flex justify-content-center">
                        <div class="col-md-3">
                            <label>* Statu:</label>
                            <input id="statu" type="text" class="form-control input-sm" />
                        </div>
                    </div>
                    @*<div class="d-flex justify-content-center">
                        <div class="col-md-3">
                            <label>* Duruş Nedeni:</label>
                            <input id="durusNedeni" type="text" class="form-control input-sm" />
                        </div>
                    </div>*@
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button onclick="SaveNoti()" type="button" class="btn btn-dark">Kaydet</button>
                </div>
            </div>

        </div>
    </div>




    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
</body>
</html>




<script>

    function SaveNoti() {
        var isNo = $("#isNo").val();
        var baslangicTarihi = $("#baslangicTarihi").val();
        var bitisTarihi = $("#bitisTarihi").val();
        var toplamSure = $("#toplamSure").val();
        var statu = $("#statu").val();
        var durusNedeni = $("#durusNedeni").val();

       
        if (isNo == "" || baslangicTarihi == "" || bitisTarihi == "" || statu == "") {
            alert("Hata ! Yıldızlı (*) alanları boş bırakmayiniz..");
            return;
        }
        $.ajax({
            url: '@Url.Action("CreateNotification", "Notifications")',
            dataType: 'json',
            data: {

                "_IsNo": isNo,
                "_BaslangicTarihi": baslangicTarihi,
                "_BitisTarihi": bitisTarihi,
                "_ToplamSure": toplamSure,
                "_Statu": statu,
                "_DurusNedeni": durusNedeni
            },

            success: function (data) {
                if (data) {
                    alert("Başarılı! Bildirim Kaydedildi");
                }
            }
        });
    }

</script>

Uretim_Operation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Uretim_Operation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Uretim_Operation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Uretim_Operation - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>